# Generated by Django 5.1 on 2024-09-19 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('cafeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cafeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_Cafeteria_System.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('cafeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_Cafeteria_System.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cafeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_Cafeteria_System.cafe')),
                ('menuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_Cafeteria_System.menu')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KPMIM_Cafeteria_System.user')),
            ],
        ),
    ]
