# Generated by Django 5.1 on 2024-09-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMIM_Cafeteria_System', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Order Received'), (1, 'Preparing'), (2, 'Ready to Pick Up'), (3, 'Picked Up')], default=0),
        ),
    ]
