# Generated by Django 5.1 on 2024-09-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMIM_Cafeteria_System', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
