# Generated by Django 5.1 on 2024-09-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPMIM_Cafeteria_System', '0004_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.IntegerField(choices=[(0, 'Not Pay'), (1, 'Paid')], default=0),
        ),
    ]
